# Generated by Django 5.1.2 on 2024-12-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
